spring:
  profiles:
      active: prov

---
server:
    address: localhost
    port: 8080
spring:
    profiles: local
    datasource:
        url: jdbc:mysql://localhost:3306/graduate?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
        username: root
        password: admin
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none



# logging.level:
   # org.hibernate.SQL: debug
# org.hibernate.type: trace

---
server:
    address: localhost
    port: 8080
spring:
    profiles: prov
    datasource:
        url: jdbc:mysql://database-1.cxq5ylgufayl.ap-northeast-2.rds.amazonaws.com/board?serverTimezone=UTC&characterEncoding=UTF-8
        username: root
        password: worjs2964
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        generate-ddl: true
        hibernate:
            ddl-auto: none



    # logging.level:
    # org.hibernate.SQL: debug
# org.hibernate.type: trace
